env:
  browser: true
  commonjs: true
  es2021: true
extends:
  - standard
parserOptions:
  ecmaVersion: 12
rules:
  arrow-parens:
    - warn
    - as-needed
    # 集成 prettier
  prettier/prettier:
    error: "always"
    singleQuote: true
    semi: false